import{prepareWorklets}from'./build-worklets.mjs';
import{build}from'esbuild';import{readFileSync,writeFileSync,mkdirSync,copyFileSync,rmSync,cpSync,existsSync}from'node:fs';import{execFileSync}from'node:child_process';
mkdirSync('public',{recursive:true});mkdirSync('generated',{recursive:true});mkdirSync('dist/server',{recursive:true});mkdirSync('dist/.openai',{recursive:true});
const worklets=prepareWorklets(),plugins=[worklets.plugin];
const bundle=await build({plugins,entryPoints:['src/widget.js'],bundle:true,write:false,platform:'browser',format:'iife',minify:true,legalComments:'inline'});const js=bundle.outputFiles[0].text;
const html=readFileSync('src/widget.html','utf8').replace('__BUNDLE__',()=>js.replaceAll('</script','<\\/script'));
writeFileSync('public/index.html',html);
const stage='/tmp/pocket-synth-source';rmSync(stage,{recursive:true,force:true});mkdirSync(stage,{recursive:true});for(const f of ['src','scripts','package.json','package-lock.json','COPYING','README.md','TESTING.md','worker'])cpSync(f,stage+'/'+f,{recursive:true});mkdirSync(stage+'/.openai',{recursive:true});writeFileSync(stage+'/.openai/hosting.json',JSON.stringify({capabilities:['mcp']}));
// Corresponding dependency source and licenses, alongside lockfile/build instructions.
mkdirSync(stage+'/dependencies',{recursive:true});for(const p of ['@strudel','@kabelsalat','fraction.js','superdough','supradough','nanostores'])if(existsSync('node_modules/'+p))cpSync('node_modules/'+p,stage+'/dependencies/'+p,{recursive:true});
execFileSync('tar',['-czf','/tmp/pocket-synth-source.tar.gz','-C',stage,'.']);
writeFileSync('generated/resources.js','export const soundHtml='+JSON.stringify(html)+';\nexport const sourceBase64='+JSON.stringify(readFileSync('/tmp/pocket-synth-source.tar.gz').toString('base64'))+';\nexport const workletSources='+JSON.stringify(worklets.sources)+';\n');
await build({entryPoints:['src/server.js'],bundle:true,outfile:'dist/server/index.js',platform:'browser',format:'esm',minify:true,legalComments:'inline'});copyFileSync('.openai/hosting.json','dist/.openai/hosting.json');await build({entryPoints:['src/sound.js'],bundle:true,outfile:'generated/sound-test.mjs',platform:'browser',format:'esm',minify:true});await build({plugins,entryPoints:['src/engine.js'],bundle:true,outfile:'generated/engine-test.mjs',platform:'browser',format:'esm',minify:false});await build({plugins,entryPoints:['scripts/audio-fixture.js'],bundle:true,outfile:'generated/audio-fixture.mjs',platform:'browser',format:'esm'});console.log('Built Strudel instrument, standalone frontend, MCP Worker and AGPL corresponding source');
