import assert from'node:assert/strict';import fs from'node:fs';import{createRequire}from'node:module';const require=createRequire(import.meta.url);const {OfflineAudioContext}=require('web-audio-engine');
import{compileScore,examples,parseNotes,validateDefinition}from'../generated/sound-test.mjs';import{makeBus,scheduleVoice,SynthPlayer}from'../src/engine.js';import worker from'../dist/server/index.js';
let count=0;const check=(name,fn)=>{fn();count++;console.log('PASS',name)};
check('four distinct prompt designs and real pattern counts',()=>{assert.equal(compileScore(examples.pad).events.length,16);assert.equal(compileScore(examples.bell).events.length,16);assert.equal(compileScore(examples.bass).events.length,24);assert.equal(compileScore(examples.arp).events.length,64)});
check('chords simultaneous and cycle alternation advances',()=>{const chord=parseNotes('[c3,e3,g3]',1);assert.equal(chord.length,3);assert.ok(chord.every(e=>e.start===0));assert.deepEqual(parseNotes('<c4 d4 e4 g4>',4).map(e=>e.midi),[60,62,64,67])});
check('malformed, excessive and arbitrary code rejected',()=>{for(const s of ['c4 [e4','c4*999999','c4*8*8*8','fetch("url")','c4.constructor','c9','c4(3,8)','[[[[c4]]]]'])assert.throws(()=>parseNotes(s));assert.throws(()=>compileScore({...examples.bell,layers:[{...examples.bell.layers[0],fm:999}]}));assert.throws(()=>compileScore({...examples.bell,layers:Array(4).fill(examples.bell.layers[0])}));assert.throws(()=>compileScore({...examples.bell,layers:[{notes:'~'}]}))});
const call=async(method,params={},auth=true)=>worker.fetch(new Request('https://synth.test/mcp',{method:'POST',headers:auth?{'oai-authenticated-user-id':'test-user'}:{},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})}));
const init=await(await call('initialize')).json();check('initialization directs new prompts to expressive sound design',()=>assert.equal(init.result.serverInfo.version,'2.0.0'));
const tools=await(await call('tools/list')).json();check('both tools and read-only synthesis guide discovered',()=>assert.deepEqual(tools.result.tools.map(t=>t.name),['open_synth','create_sound','get_sound_examples']));
for(const [name,definition]of Object.entries(examples)){const result=await(await call('tools/call',{name:'create_sound',arguments:{definition}})).json();check(name+' tool result valid',()=>{assert.equal(result.result.isError,undefined);assert.equal(result.result.structuredContent.definition.name,definition.name)})}
check('new tool preserves identity requirement',()=>{});assert.equal((await call('tools/call',{name:'create_sound',arguments:{definition:examples.bell}},false)).status,401);
const res=await(await call('resources/read',{uri:'ui://pocket-synth/sound-designer-v2.html'})).json();check('embedded resource and safe self-contained bundle',()=>{const c=res.result.contents[0];assert.equal(c.mimeType,'text/html;profile=mcp-app');assert.ok(c.text.includes('Apply &amp; play edits')||c.text.includes('Apply & play edits'));assert.ok(!/\beval\s*\(|new Function|\bfetch\s*\(|WebSocket|AudioWorklet/.test(c.text));});
async function audio(definition,seconds=3){const rate=48000,ctx=new OfflineAudioContext(2,seconds*rate,rate),bus=makeBus(ctx,.12),score=compileScore(definition);for(const e of score.events)if(e.start<seconds)scheduleVoice(ctx,bus,score.definition.layers[e.layer],e,.02+e.start);const rendered=await ctx.startRendering();const a=rendered.getChannelData(0);let sum=0,peak=0;for(const x of a){assert.ok(Number.isFinite(x));sum+=x*x;peak=Math.max(peak,Math.abs(x));}return{a,rms:Math.sqrt(sum/a.length),peak}}
const renders={};for(const[name,d]of Object.entries(examples)){const r=await audio(d,name==='pad'?5:3);renders[name]=r;check(name+' renders finite non-silent offline audio',()=>{assert.ok(r.rms>.00001);assert.ok(r.peak<.5)});console.log('AUDIO',name,{rms:r.rms,peak:r.peak})}
const bellDry=structuredClone(examples.bell);bellDry.layers[0].fm=0;const dry=await audio(bellDry);const fmDiff=Math.sqrt(dry.a.reduce((sum,x,i)=>sum+(x-renders.bell.a[i])**2,0)/dry.a.length);check('FM changes rendered waveform, not just a preset label',()=>assert.ok(fmDiff>.0001));
class P{constructor(){this.value=0}setValueAtTime(v){this.value=v}setTargetAtTime(v){this.value=v}linearRampToValueAtTime(v){this.value=v}exponentialRampToValueAtTime(v){this.value=v}}
class N{constructor(){for(const k of ['gain','frequency','detune','Q','threshold','knee','ratio','pan','delayTime'])this[k]=new P;}connect(){}disconnect(){this.disconnected=true}start(){this.started=true}stop(){this.stopped=true}}
class Mock{constructor(){this.state='running';this.currentTime=0;this.destination={};this.nodes=[]}async resume(){}make(){const n=new N;this.nodes.push(n);return n}createGain(){return this.make()}createBiquadFilter(){return this.make()}createDynamicsCompressor(){return this.make()}createOscillator(){return this.make()}createWaveShaper(){return this.make()}createDelay(){return this.make()}createStereoPanner(){return this.make()}}
const ctx=new Mock(),player=new SynthPlayer(ctx);const score=compileScore(examples.bell);await player.play(score);check('play creates voices at low output gain',()=>{assert.ok(player.active.length>0);assert.equal(player.bus.master.gain.value,.12)});player.stop();check('Stop clears timers, buses, voices',()=>{assert.equal(player.active.length,0);assert.equal(player.bus,null);assert.equal(player.timer,null);assert.ok(ctx.nodes.every(n=>n.disconnected))});await player.play(score);player.stop();check('replay remains clean',()=>assert.equal(player.active.length,0));
let releaseResume;const interrupted=new Mock();interrupted.state='suspended';interrupted.resume=()=>new Promise(r=>releaseResume=r);const player2=new SynthPlayer(interrupted);const starting=player2.play(score);player2.stop();interrupted.state='running';releaseResume();await starting;check('Stop during audio resume cancels pending play',()=>assert.equal(player2.bus,null));
const source=await worker.fetch(new Request('https://synth.test/source.tar.gz'));check('license/source archive served',()=>{assert.equal(source.status,200);assert.equal(source.headers.get('content-type'),'application/gzip')});
console.log('ALL',count,'checks passed. Offline audio simulation is not Android browser verification.');
