import assert from 'node:assert/strict';import {createRequire} from 'node:module';import fs from'node:fs';const require=createRequire(import.meta.url);
const W=require('web-audio-engine'),api=require('web-audio-engine/lib/api');Object.assign(globalThis,api,{OfflineAudioContext:W.OfflineAudioContext,AudioContext:W.RenderingAudioContext,AudioWorkletNode:class{}});
// The test engine implements Web Audio, not a browser. These are real DSP renders.
const S=await import('../generated/audio-fixture.mjs');const {buildPattern,examples,compileScore,parseNotes}=S;let count=0;function check(name,fn){fn();count++;console.log('PASS',name)}
check('Strudel pattern contains real SuperDough voice controls',()=>{const h=buildPattern(examples.bell).queryArc(0,1);assert.equal(h.length,8);assert.equal(h[0].value.s,'sine');assert.equal(h[0].value.fmi,4.2);assert.equal(h[0].value.fmh,2.71)});
check('alternating cycles and chords',()=>{assert.deepEqual(parseNotes('<c4 d4 e4>',3).map(e=>e.midi),[60,62,64]);assert.equal(parseNotes('[c4,e4,g4]',1).length,3)});
check('bad input cannot evaluate code or overload expansion',()=>{for(const p of ['c4 [e4','c4*999','c4*8*8*8','fetch("x")','[[[[c4]]]]','c9'])assert.throws(()=>parseNotes(p));assert.throws(()=>compileScore({...examples.bell,layers:[{notes:'~'}]}));assert.throws(()=>compileScore({...examples.bell,bpm:NaN}))});
async function render(d,seconds=3){const {execFileSync}=await import('node:child_process');const path='/tmp/pocket-render.json';execFileSync(process.execPath,['scripts/render-audio.mjs',JSON.stringify(d),String(seconds),path],{stdio:['ignore','pipe','inherit']});return JSON.parse(fs.readFileSync(path,'utf8'))}
let bell;for(const [name,d]of Object.entries(examples)){const r=await render(d,name==='pad'?5:3);if(name==='bell')bell=r;check(name+' official SuperDough voice/envelope/FM/echo output finite/non-silent/bounded',()=>{assert.ok(r.rms>1e-5,JSON.stringify(r));assert.ok(r.peak<.5)});console.log('AUDIO',name,{rms:r.rms,peak:r.peak})}
const dry=structuredClone(examples.bell);dry.layers[0].fm=0;const r=await render(dry);check('FM materially changes actual engine output',()=>assert.ok(Math.sqrt(r.a.reduce((s,x,i)=>s+(x-bell.a[i])**2,0)/r.a.length)>1e-4));
const worker=(await import('../dist/server/index.js')).default;const call=async(method,params={},auth=true)=>worker.fetch(new Request('https://instrument.test/mcp',{method:'POST',headers:auth?{'oai-authenticated-user-id':'test'}:{},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})}));
const init=await(await call('initialize')).json();check('v3 MCP initialization',()=>assert.equal(init.result.serverInfo.version,'3.0.0'));const tools=await(await call('tools/list')).json();check('backward-compatible tool identities',()=>assert.deepEqual(tools.result.tools.map(t=>t.name),['open_synth','create_sound','get_sound_examples']));
for(const[name,definition]of Object.entries(examples)){const r=await(await call('tools/call',{name:'create_sound',arguments:{definition}})).json();check('MCP accepts '+name,()=>assert.equal(r.result.structuredContent.definition.name,definition.name))}
check('unauthenticated data tool denied',()=>{});assert.equal((await call('tools/call',{name:'create_sound',arguments:{definition:examples.pad}},false)).status,401);
const page=await worker.fetch(new Request('https://instrument.test/')),html=await page.text();check('normal frontend and chat use exact same instrument',()=>{assert.equal(page.status,200);assert.ok(html.includes('Save on this device'));assert.ok(html.includes('SuperDough'));assert.equal(html,fs.readFileSync('public/index.html','utf8'))});
check('source archive available',()=>{});assert.equal((await worker.fetch(new Request('https://instrument.test/source.tar.gz'))).status,200);
await import('./test-worklets.mjs');
console.log('ALL',count,'checks passed. Browser/device audio QA is separate.');
