// Pocket Synth, AGPL-3.0-or-later. See COPYING and /source.tar.gz.
import legacy,{synthTool,resourceUri,widgetHtml as legacyHtml}from'./legacy.js';
import{definitionSchema,compileScore,examples}from'./sound.js';import{soundHtml,sourceBase64,workletSources}from'../generated/resources.js';
import{assetOrigin,htmlWithAssetOrigin,resourceWithAssets,serveWorklet}from'./hosted-assets.js';
const uri='ui://pocket-synth/sound-designer-v3-worklets.html';
const previousUri='ui://pocket-synth/sound-designer-v2.html';
const soundTool={name:'create_sound',title:'Create a playable synth sound',description:'Translate the user’s natural-language sound request into a synthesis definition and display it for playback and editing in chat. Design the actual parameters, not just a preset label. Up to 3 layered subtractive/FM synths; Strudel Cyclist scheduling and official SuperDough synthesis with mini-notation notes/chords/rests/cycle alternations. One cycle is 4 beats; 1–8 cycle phrase length. Playback loops until Stop by default. For examples and supported parameter ranges call get_sound_examples. No samples, vocals, audio imitation or arbitrary JavaScript. Preserve unrelated parameters during refinements. Tool returns an editable sound definition; user taps Play. Distortion=drive, brightness=cutoff, metallicness=fm and fmRatio, movement=filterMotion/filterRate, echo=delay. Omitted layer fields have defaults.',inputSchema:{type:'object',additionalProperties:false,required:['definition'],properties:{definition:definitionSchema}},annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false},_meta:{ui:{resourceUri:uri},'openai/outputTemplate':uri,'openai/toolInvocation/invoking':'Designing the sound','openai/toolInvocation/invoked':'Sound ready to play'}};
const examplesTool={name:'get_sound_examples',title:'Get synthesis examples',description:'Read four complete examples and synthesis limits before designing a new prompt-generated sound: warm layered analog pad, glassy FM bell, gritty bass, evolving arpeggio. Examples are editable starting points, not the limit of available combinations.',inputSchema:{type:'object',additionalProperties:false,properties:{}},annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}};
const resource={uri,name:'sound-designer',title:'Pocket Synth sound designer',mimeType:'text/html;profile=mcp-app',_meta:{ui:{prefersBorder:true,csp:{connectDomains:[],resourceDomains:[]}},'openai/widgetDescription':'Play and edit a prompt-generated layered synth definition with real Strudel note patterns, FM and timbre controls.'}};
const reply=(id,result)=>Response.json({jsonrpc:'2.0',id,result},{headers:{'Cache-Control':'no-store'}});
export default{async fetch(request,env){const path=new URL(request.url).pathname;const workletResponse=serveWorklet(request,workletSources);if(workletResponse)return workletResponse;if(path==='/'||path==='/instrument')return new Response(env?.POCKET_SYNTH_ASSET_ORIGIN?htmlWithAssetOrigin(soundHtml,assetOrigin(request,env.POCKET_SYNTH_ASSET_ORIGIN)):soundHtml,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}});if(path==='/source.tar.gz'){const bytes=Uint8Array.from(atob(sourceBase64),c=>c.charCodeAt(0));return new Response(bytes,{headers:{'Content-Type':'application/gzip','Content-Disposition':'attachment; filename="pocket-synth-v3-source.tar.gz"','Cache-Control':'no-store'}});}if(path!=='/mcp'||request.method!=='POST')return legacy.fetch(request);let body;try{const text=await request.clone().text();if(text.length>24000)return new Response('Request too large',{status:413});body=JSON.parse(text)}catch{return legacy.fetch(request)}if(!body||body.jsonrpc!=='2.0'||body.id===undefined)return legacy.fetch(request);const id=body.id;
if(body.method==='initialize')return reply(id,{protocolVersion:'2025-06-18',capabilities:{tools:{},resources:{}},serverInfo:{name:'pocket-synth',version:'3.0.0'},instructions:'For natural-language sound design use get_sound_examples as reference, then create_sound with a complete custom synthesis definition. Shape actual FM, envelopes, filters and note patterns to match the prompt. The user can play and edit it in chat. open_synth is retained only for the original simple pad interface. Never claim a sound is playing until the user taps Play.'});
if(body.method==='tools/list')return reply(id,{tools:[synthTool,soundTool,examplesTool]});
if(body.method==='resources/list')return reply(id,{resources:[{uri:resourceUri,name:'pocket-synth',mimeType:'text/html;profile=mcp-app'},resourceWithAssets(resource,assetOrigin(request,env?.POCKET_SYNTH_ASSET_ORIGIN))]});
if(body.method==='resources/read'&&[uri,previousUri].includes(body.params?.uri)){const origin=assetOrigin(request,env?.POCKET_SYNTH_ASSET_ORIGIN);return reply(id,{contents:[{...resourceWithAssets(resource,origin,body.params.uri),text:htmlWithAssetOrigin(soundHtml,origin)}]});}
if(body.method==='tools/call'&&['create_sound','get_sound_examples'].includes(body.params?.name)){if(!request.headers.get('oai-authenticated-user-id'))return new Response('Sign in to use your private synth',{status:401});if(body.params.name==='get_sound_examples')return reply(id,{content:[{type:'text',text:JSON.stringify({examples,schema:definitionSchema,limits:'Real Strudel mini-notation subset. No user JavaScript, samples or remote audio requests. FM is actual oscillator frequency modulation; 48 concurrent SuperDough voices max; two detuned voices per note. Sound definition is editable in the widget. AGPL-3.0-or-later.'})}],structuredContent:{examples,schema:definitionSchema}});try{const args=body.params.arguments;if(!args||typeof args!=='object'||Object.keys(args).some(k=>k!=='definition'))throw Error('Expected a definition object');const score=compileScore(args.definition);return reply(id,{content:[{type:'text',text:`${score.definition.name}: ${score.definition.layers.length} synth layer(s), ${score.events.length} notes. Tap Play to hear the sound; edit the definition or timbre controls in chat.`}],structuredContent:{definition:score.definition,notes:score.events.length,durationSeconds:score.duration},_meta:{ui:{resourceUri:uri}}});}catch(e){return reply(id,{isError:true,content:[{type:'text',text:e.message||'Invalid sound definition'}]});}}
return legacy.fetch(request);}};
