// Pocket Synth, 2026-10-02. AGPL-3.0-or-later. See COPYING.
import {mini} from '@strudel/mini';
import {stack} from '@strudel/core';
export const ranges={gain:[0,.5],attack:[.005,6],decay:[.01,6],sustain:[0,1],release:[.02,6],cutoff:[80,16000],resonance:[.1,8],detune:[0,35],fm:[0,12],fmRatio:[.1,12],fmDecay:[.01,6],fmSustain:[0,1],drive:[0,1],delay:[0,.5],pan:[-1,1],filterMotion:[0,1],filterRate:[.02,4],gate:[.1,2]};
export const layerDefaults={label:'Synth',notes:'c4 e4 g4 b4',waveform:'sine',gain:.3,attack:.02,decay:.4,sustain:.4,release:.4,cutoff:7000,resonance:.7,detune:0,fm:0,fmRatio:2,fmDecay:.3,fmSustain:0,drive:0,delay:0,pan:0,filterMotion:0,filterRate:.2,gate:.85};
export const examples={
 pad:{name:'Warm analog shimmer pad',bpm:60,cycles:2,layers:[{...layerDefaults,label:'Warm body',notes:'[c3,e3,g3,b3]',waveform:'sawtooth',gain:.22,attack:2.4,decay:1,sustain:.75,release:2.8,cutoff:2200,detune:9,filterMotion:.25,filterRate:.1,gate:1},{...layerDefaults,label:'Shimmer',notes:'[c5,e5,g5,b5]',waveform:'sine',gain:.06,attack:2.8,decay:1,sustain:.6,release:3,cutoff:9000,delay:.2,gate:1}]},
 bell:{name:'Plucky glass FM bell',bpm:85,cycles:4,layers:[{...layerDefaults,label:'Glass',notes:'c5 ~ e5 ~ g5 ~ b5 ~',gain:.3,attack:.005,decay:1.1,sustain:0,release:.8,cutoff:12000,fm:4.2,fmRatio:2.71,fmDecay:.65,fmSustain:0,delay:.15,gate:1.5}]},
 bass:{name:'Gritty syncopated bass',bpm:112,cycles:4,layers:[{...layerDefaults,label:'Grit',notes:'c2 c2 ~ [c2 g1] ~ eb2 g1 ~',waveform:'sawtooth',gain:.3,attack:.008,decay:.18,sustain:.25,release:.12,cutoff:900,resonance:2,detune:5,fm:.3,fmRatio:1,drive:.6,gate:.65}]},
 arp:{name:'Evolving luminous arpeggio',bpm:105,cycles:8,layers:[{...layerDefaults,label:'Arpeggio',notes:'<c4 d4 e4 g4> [e4 g4 b4 e5] <g4 a4 b4 d5> [b4 g4]',waveform:'triangle',gain:.3,attack:.01,decay:.3,sustain:.2,release:.35,cutoff:2800,fm:1.2,fmRatio:2,delay:.24,filterMotion:.75,filterRate:.13,gate:.7}]}
};
export const definitionSchema={type:'object',additionalProperties:false,required:['name','bpm','cycles','layers'],properties:{name:{type:'string',minLength:1,maxLength:80},bpm:{type:'number',minimum:30,maximum:200},cycles:{type:'integer',minimum:1,maximum:8},layers:{type:'array',minItems:1,maxItems:3,items:{type:'object',additionalProperties:false,required:['notes'],properties:{label:{type:'string',maxLength:40},notes:{type:'string',minLength:1,maxLength:512,description:'Restricted real Strudel mini-notation: note names c1–b7, #/b accidentals, rests ~, sequences, [subdivisions], [chords,with,commas], <cycle alternation>, *1..8 repeats and /1..8 slowing. No JavaScript.'},waveform:{type:'string',enum:['sine','triangle','sawtooth','square']},...Object.fromEntries(Object.entries(ranges).map(([k,[minimum,maximum]])=>[k,{type:'number',minimum,maximum}]))}}}}};
function number(v,lo,hi,label){if(typeof v!=='number'||!Number.isFinite(v)||v<lo||v>hi)throw Error(label+' must be '+lo+'–'+hi);return v;}
export function noteMidi(note){const m=String(note).match(/^([a-g])([#b]?)([1-7])$/i);if(!m)throw Error('Use note names with octaves, such as c4 or f#3');return(Number(m[3])+1)*12+{c:0,d:2,e:4,f:5,g:7,a:9,b:11}[m[1].toLowerCase()]+(m[2]==='#'?1:m[2]==='b'?-1:0);}
export function parseNotes(notes,cycles=8){if(typeof notes!=='string'||!notes.trim()||notes.length>512)throw Error('Notes must contain 1–512 characters');const tokens=notes.match(/[a-g](?:#|b)?[1-7]|~|[\[\]<>,]|[*/][1-8](?!\d)/gi)||[];if(tokens.join('')!==notes.replace(/\s/g,''))throw Error('Unsupported notes syntax. Use note names, ~, [], <>, commas, *1–8 or /1–8');if(tokens.length>128)throw Error('Keep the pattern under 128 tokens');let depth=0,expansion=1;for(const t of tokens){if(t==='['||t==='<'){if(++depth>3)throw Error('Maximum pattern nesting is 3');}if(t===']'||t==='>')depth--;if(depth<0)throw Error('Unbalanced pattern brackets');if(t[0]==='*')expansion*=Number(t.slice(1));if(expansion>32)throw Error('Pattern repeats exceed the safe limit');}if(depth!==0)throw Error('Unbalanced pattern brackets');let p;try{p=mini(notes)}catch{throw Error('Invalid Strudel mini-notation');}const events=p.queryArc(0,cycles).filter(h=>h.whole&&Number(h.whole.begin)>=0).map(h=>({midi:noteMidi(h.value),start:Number(h.whole.begin),duration:Number(h.whole.end.sub(h.whole.begin))}));if(events.length>256)throw Error('Maximum 256 notes per layer');for(let c=0;c<cycles;c++)if(events.filter(e=>e.start>=c&&e.start<c+1).length>64)throw Error('Maximum 64 notes per cycle');return events.sort((a,b)=>a.start-b.start);}
export function validateDefinition(input){if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Sound definition must be an object');for(const k of Object.keys(input))if(!['name','bpm','cycles','layers'].includes(k))throw Error('Unknown sound field: '+k);if(typeof input.name!=='string'||!input.name.trim()||input.name.length>80)throw Error('Name must contain 1–80 characters');const bpm=number(input.bpm,30,200,'bpm'),cycles=number(input.cycles,1,8,'cycles');if(!Number.isInteger(cycles))throw Error('cycles must be an integer');if(!Array.isArray(input.layers)||!input.layers.length||input.layers.length>3)throw Error('Use 1–3 synth layers');const layers=input.layers.map((raw,i)=>{if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error('Invalid layer');if(typeof raw.notes!=='string')throw Error('Each layer needs a notes pattern');const l={...layerDefaults,...raw};for(const k of Object.keys(raw))if(!Object.hasOwn(layerDefaults,k))throw Error('Unknown layer field: '+k);if(typeof l.label!=='string'||l.label.length>40)throw Error('Layer label too long');if(!['sine','triangle','sawtooth','square'].includes(l.waveform))throw Error('Unsupported oscillator');for(const[k,[lo,hi]]of Object.entries(ranges))number(l[k],lo,hi,`Layer ${i+1} ${k}`);parseNotes(l.notes,8);return l;});return{name:input.name.trim(),bpm,cycles,layers};}
export function compileScore(input){const definition=validateDefinition(input),cycleSeconds=240/definition.bpm;const events=definition.layers.flatMap((l,i)=>parseNotes(l.notes,definition.cycles).map(e=>({...e,layer:i,start:e.start*cycleSeconds,duration:Math.min(10,e.duration*cycleSeconds*l.gate)}))).sort((a,b)=>a.start-b.start);if(events.length>512)throw Error('Maximum 512 total notes');if(!events.length)throw Error('The pattern contains only rests');const total=definition.cycles*cycleSeconds;return{definition,events:events.filter(e=>e.start<total),duration:total};}

// Compile controls into real Strudel patterns. Cyclist queries these continuously.
// No pre-rendered event loop or custom oscillator renderer is involved.
export function buildPattern(input){
 const d=validateDefinition(input);
 return stack(...d.layers.flatMap((l,i)=>[-1,1].map(sign=>mini(l.notes).fmap(note=>({
  note:noteMidi(note)+sign*l.detune/100,s:l.waveform,gain:l.gain*.5,
  attack:l.attack,decay:l.decay,sustain:l.sustain,release:l.release,
  cutoff:l.cutoff,resonance:l.resonance,ftype:'12db',
  fmi:l.fm,fmh:l.fmRatio,fmattack:.001,fmdecay:l.fmDecay,fmsustain:l.fmSustain,fmrelease:l.release,
  ...(l.drive>0?{distort:l.drive,distortvol:.7}:{}),pan:(l.pan+1)/2,
  delay:l.delay,delaytime:60/d.bpm*.5,delayfeedback:.28,orbit:i,
  ...(l.filterMotion>0?{lprate:l.filterRate,lpdepth:l.filterMotion*2}:{}),legato:l.gate
 })))));
}
