// Pocket Synth 3 · 2026-10-05 · AGPL-3.0-or-later
import{compileScore,examples}from'./sound.js';import{SynthPlayer}from'./engine.js';
const $=id=>document.getElementById(id),copy=x=>JSON.parse(JSON.stringify(x));let definition=copy(examples.pad),layerIndex=0,bridge=false,rpcId=0;const pending=new Map();
const controls=[['tone','cutoff','Cutoff',80,16000,20,'Hz'],['tone','resonance','Resonance',.1,8,.1,''],['tone','detune','Unison detune',0,35,1,'ct'],['tone','fm','FM index',0,12,.1,''],['tone','fmRatio','FM ratio',.1,12,.01,'×'],['tone','filterMotion','Filter motion',0,1,.01,''],['envelope','attack','Attack',.005,6,.001,'s'],['envelope','decay','Decay',.01,6,.01,'s'],['envelope','sustain','Sustain',0,1,.01,''],['envelope','release','Release',.02,6,.001,'s'],['envelope','gate','Gate',.1,2,.05,'×'],['mix','drive','Drive',0,1,.01,''],['mix','delay','Echo',0,.5,.01,''],['mix','pan','Pan',-1,1,.05,''],['mix','gain','Layer level',0,.5,.01,'']];
for(const[group,key,label,min,max,step,unit]of controls){const l=document.createElement('label');l.textContent=label;const o=document.createElement('output');o.id=key+'Out';const input=document.createElement('input');Object.assign(input,{type:'range',id:key,min,max,step});input.setAttribute('aria-label',label);l.append(o,input);$(group).append(l);input.oninput=()=>{const next=copy(definition);next.layers[layerIndex][key]=Number(input.value);commit(next,false);o.textContent=format(Number(input.value),unit);};input.onchange=()=>publish();}
function format(v,unit){if(unit==='s'&&v<1)return Math.round(v*1000)+' ms';return(unit==='Hz'?Math.round(v):Number(v.toFixed(2)))+(unit?' '+unit:'');}
function showError(e){$('error').textContent=e?.message||String(e)}
const player=new SynthPlayer(state=>{$('status').textContent=state==='Playing'?'Playing · edits affect the next notes':state==='Playing (native)'?'Playing · compatible Web Audio mode':state==='Starting'?'Starting audio…':'Stopped';$('play').disabled=state==='Starting';$('play').textContent=state.startsWith('Playing')?'▶ Playing':'▶ Play';},showError);
function storageRead(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function storageWrite(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch{$('saveNotice').textContent='Storage unavailable. Use Export to keep this patch.';return false}}
function render(){const d=definition;$('name').textContent=d.name;$('patchName').value=d.name;$('bpm').value=d.bpm;const l=d.layers[layerIndex];$('layer').replaceChildren(...d.layers.map((l,i)=>{const op=document.createElement('option');op.value=i;op.textContent=String(i+1).padStart(2,'0')+' / '+l.label;return op}));$('layer').value=layerIndex;$('waveform').value=l.waveform;$('notes').value=l.notes;for(const[,k,,,,,unit]of controls){$(k).value=l[k];$(k+'Out').textContent=format(l[k],unit)}$('definition').value=JSON.stringify(d,null,2);}
function commit(input,redraw=true){try{const next=compileScore(input).definition;player.update(next);definition=next;layerIndex=Math.min(layerIndex,next.layers.length-1);$('error').textContent='';if(redraw)render();else $('definition').value=JSON.stringify(definition,null,2);storageWrite('pocket-synth-v3-current',definition);return true}catch(e){showError(e);return false}}
function load(input){if(commit(input)){layerIndex=0;render();publish()}}
function play(){player.play(definition,$('loop').checked)}
$('play').onclick=play;$('stop').onclick=()=>player.stop();$('panic').onclick=()=>{player.stop();$('status').textContent='Panic · all audio disconnected'};$('loop').onchange=()=>player.setLoop($('loop').checked);
$('volume').oninput=()=>{const v=Number($('volume').value);player.setVolume(v);$('volumeOut').textContent=v?Math.round(20*Math.log10(v))+' dB':'−∞ dB'};
$('layer').onchange=()=>{layerIndex=Number($('layer').value);render()};$('waveform').onchange=()=>{const next=copy(definition);next.layers[layerIndex].waveform=$('waveform').value;commit(next);publish()};$('bpm').onchange=()=>{const next=copy(definition);next.bpm=Number($('bpm').value);if(!commit(next))$('bpm').value=definition.bpm;publish()};
$('applyNotes').onclick=()=>{const next=copy(definition);next.layers[layerIndex].notes=$('notes').value;if(commit(next))publish()};
$('apply').onclick=()=>{try{load(JSON.parse($('definition').value))}catch(e){showError(Error('Invalid JSON: '+e.message))}};
for(const b of document.querySelectorAll('[data-example]'))b.onclick=()=>load(copy(examples[b.dataset.example]));
function refreshBank(){const bank=storageRead('pocket-synth-v3-bank',{});$('saved').replaceChildren(new Option('Select a patch…',''),...Object.keys(bank).map(name=>new Option(name,name)))}
$('save').onclick=()=>{const next=copy(definition);next.name=$('patchName').value.trim();if(!commit(next))return;const bank=Object.assign(Object.create(null),storageRead('pocket-synth-v3-bank',{}));bank[definition.name]=definition;if(storageWrite('pocket-synth-v3-bank',bank)){$('saveNotice').textContent='Saved on this device';refreshBank();$('saved').value=definition.name;publish()}};
$('saved').onchange=()=>{const patch=storageRead('pocket-synth-v3-bank',{})[$('saved').value];if(patch)load(patch)};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({format:'pocket-synth',version:3,definition},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=definition.name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);$('saveNotice').textContent='Patch export created'};
$('import').onclick=()=>$('file').click();$('file').onchange=async()=>{const file=$('file').files[0];try{if(!file)return;if(file.size>32000)throw Error('Patch file exceeds 32 KB');const json=JSON.parse(await file.text());load(json.definition??json)}catch(e){showError(Error('Import failed: '+e.message))}finally{$('file').value=''}};
function notify(method,params){if(window.parent!==window)window.parent.postMessage({jsonrpc:'2.0',method,params},'*')}
function rpc(method,params){return new Promise((resolve,reject)=>{const id=++rpcId,timer=setTimeout(()=>{pending.delete(id);reject(Error('Chat connection timeout'))},5000);pending.set(id,{resolve,reject,timer});window.parent.postMessage({jsonrpc:'2.0',id,method,params},'*')})}
function resize(){if(bridge)notify('ui/notifications/size-changed',{height:document.documentElement.scrollHeight})}
function publish(){if(bridge)rpc('ui/update-model-context',{content:[{type:'text',text:'Current Pocket Synth patch: '+JSON.stringify(definition)}]}).catch(()=>{});try{window.openai?.setWidgetState?.({definition})}catch{}resize()}
window.addEventListener('message',e=>{if(e.source!==window.parent||e.data?.jsonrpc!=='2.0')return;const m=e.data;if(pending.has(m.id)){const p=pending.get(m.id);clearTimeout(p.timer);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);return}if(m.method==='ui/notifications/tool-result'&&m.params?.structuredContent?.definition)load(m.params.structuredContent.definition);if(m.method==='ui/notifications/tool-input'&&m.params?.arguments?.definition)load(m.params.arguments.definition);if(m.method==='ui/resource-teardown'){player.stop();if(m.id!==undefined)window.parent.postMessage({jsonrpc:'2.0',id:m.id,result:{}},'*')}});
window.addEventListener('keydown',e=>{if(e.key==='Escape'){player.stop();return}if(e.code==='Space'&&!/INPUT|TEXTAREA|SELECT|BUTTON/.test(document.activeElement?.tagName)){e.preventDefault();player.running?player.stop():play()}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)player.stop()});window.addEventListener('pagehide',()=>player.stop());for(const d of document.querySelectorAll('details'))d.ontoggle=resize;
const saved=storageRead('pocket-synth-v3-current',null);if(saved){try{definition=compileScore(saved).definition}catch{}}render();refreshBank();if(window.openai?.toolOutput?.definition)load(window.openai.toolOutput.definition);
if(window.parent!==window)rpc('ui/initialize',{appInfo:{name:'pocket-synth',version:'3.0.0'},appCapabilities:{},protocolVersion:'2026-01-26'}).then(()=>{bridge=true;notify('ui/notifications/initialized',{});resize()}).catch(()=>{});
const canvas=$('scope'),draw=canvas.getContext('2d'),samples=new Float32Array(1024);function frame(){draw.clearRect(0,0,canvas.width,canvas.height);draw.strokeStyle='#c9ee88';draw.lineWidth=2;draw.beginPath();if(player.meter)player.meter.getFloatTimeDomainData(samples);else samples.fill(0);for(let i=0;i<samples.length;i++){const x=i/samples.length*canvas.width,y=(.5-samples[i]*2)*canvas.height;i?draw.lineTo(x,y):draw.moveTo(x,y)}draw.stroke();const pos=player.position();$('position').textContent='BAR '+String(Math.floor(pos)+1).padStart(3,'0')+' · BEAT '+(Math.floor((pos%1)*4)+1);requestAnimationFrame(frame)}frame();
